[package]
name = "hash_benchmark-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.3"
byteorder = "1.4.3"
murmur3 = "0.4.1"
rand = "0.8.5"
seahash = "4.1.0"
